site_name: Christopher Blake
site_description: I make things and very occasionally write about them.
site_url: https://cjblake.net/
site_author: Christopher Blake

repo_url: https://github.com/cj13579/personal-site/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
  language: en
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - content.code.copy

plugins:
  - blog
nav:
  - projects.md
  - blog/index.md
  - sql2pgrest: sql2pgrest.md

markdown_extensions: 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - neoteroi.timeline

extra_javascript:
  - javascripts/sql2pgrest.js

extra_css:
  - stylesheets/neoteroi-timeline.css
